# source: https://github.com/sphinx-notes/pages
name: Deploy Docs

on:
  push:
    branches: [docs-deploy, main] # branch to trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        

    steps:
      - uses: actions/checkout@v2

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: deploy-docs-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            deploy-docs-


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
    
      

  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: pandoc-install
      run: |
        sudo apt install -y pandoc

    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/
        requirements_path: ./docs/requirements.txt
