name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  build-and-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: deploy-docs-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            deploy-docs-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Graphviz, Pandoc, and LaTeX
        run: |
          sudo apt update
          sudo apt install -y graphviz pandoc texlive texlive-latex-extra texlive-fonts-recommended dvipng
  
      - id: pandoc-install
        run: |
          sudo apt install -y pandoc
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: ./docs/
          requirements_path: ./docs/requirements.txt
    

      # - name: Build Sphinx Documentation
      #   working-directory: ./docs
      #   run: make html

      # - name: Deploy to GitHub Pages
      #   uses: sphinx-notes/pages@v3
      #   with:
      #     documentation_path: docs/_build/html
      #     requirements_path: docs/requirements.txt
